apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cnvrg
parameters:
  svStorageClass: vsan-default-storage-policy
  csi.storage.k8s.io/fstype: "ext4"
provisioner: csi.vsphere.vmware.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
