registry:
  user: cnvrghelm
controlPlane:
  image: cnvrg/app:v3.12.17
  baseConfig:
    featureFlags:
      CNVRG_MOUNT_HOST_FOLDERS: false
  mpi:
    registry:
      user: cnvrghelm
clusterDomain: cnvrg.demo.local
dbs:
  redis:
    storageClass: cnvrg
  minio:
    storageClass: cnvrg
  pg:
    storageClass: cnvrg
  es:
    storageClass: cnvrg
logging:
  elastalert:
    storageClass: cnvrg
monitoring:
  prometheus:
    storageClass: cnvrg
